set(kconfig_env_dirs)
list(APPEND kconfig_env_dirs ZEPHYR_FENTON_MODULE_DIR=C:/ELI/prj/voltvision/fenton-fum/fum-powerdoor-fw-west/fenton)
list(APPEND kconfig_env_dirs ZEPHYR_EGFX_MODULE_DIR=C:/ELI/prj/voltvision/fenton-fum/fum-powerdoor-fw-west/egfx)
list(APPEND kconfig_env_dirs ZEPHYR_E_MODULE_DIR=C:/ELI/prj/voltvision/fenton-fum/fum-powerdoor-fw-west/e)
list(APPEND kconfig_env_dirs ZEPHYR_CMSIS_MODULE_DIR=C:/ELI/prj/voltvision/fenton-fum/fum-powerdoor-fw-west/modules/hal/cmsis)
list(APPEND kconfig_env_dirs ZEPHYR_CMSIS_6_MODULE_DIR=C:/ELI/prj/voltvision/fenton-fum/fum-powerdoor-fw-west/modules/hal/cmsis_6)
list(APPEND kconfig_env_dirs ZEPHYR_HAL_ESPRESSIF_MODULE_DIR=C:/ELI/prj/voltvision/fenton-fum/fum-powerdoor-fw-west/modules/hal/espressif)
list(APPEND kconfig_env_dirs ZEPHYR_HAL_NXP_MODULE_DIR=C:/ELI/prj/voltvision/fenton-fum/fum-powerdoor-fw-west/modules/hal/nxp)
list(APPEND kconfig_env_dirs ZEPHYR_LIBMETAL_MODULE_DIR=C:/ELI/prj/voltvision/fenton-fum/fum-powerdoor-fw-west/modules/hal/libmetal)
list(APPEND kconfig_env_dirs ZEPHYR_MBEDTLS_MODULE_DIR=C:/ELI/prj/voltvision/fenton-fum/fum-powerdoor-fw-west/modules/crypto/mbedtls)
list(APPEND kconfig_env_dirs ZEPHYR_OPEN_AMP_MODULE_DIR=C:/ELI/prj/voltvision/fenton-fum/fum-powerdoor-fw-west/modules/lib/open-amp)
list(APPEND kconfig_env_dirs ZEPHYR_SEGGER_MODULE_DIR=C:/ELI/prj/voltvision/fenton-fum/fum-powerdoor-fw-west/modules/debug/segger)
list(APPEND kconfig_env_dirs ZEPHYR_ZCBOR_MODULE_DIR=C:/ELI/prj/voltvision/fenton-fum/fum-powerdoor-fw-west/modules/lib/zcbor)
