#ifndef _E__SHELL_H_
#define _E__SHELL_H_

#include "stdint.h"
#include "stdbool.h"
#include "e_config.h"

typedef enum _fun_key_status
{
    kSHELL_Normal = 0U,   /*!< Normal key */
    kSHELL_Special = 1U,  /*!< Special key */
    kSHELL_Function = 2U, /*!< Function key */
} fun_key_status_t;

typedef int32_t (*cmd_function_t)(const void * shell_context, int32_t argc, char **argv);

typedef struct _shell_command_context
{
    char *pcCommand; /*!< The command that is executed.  For example "help".  It must be all lower case. */
    char *pcHelpString;    /*!< String that describes how to use the command.  It should start with the command itself,
                                    and end with "\r\n".  For example "help: Returns a list of all the commands\r\n". */
    cmd_function_t  pFuncCallBack; /*!< A pointer to the callback function that returns the output generated by the command. */

    uint32_t MinPrivilegeLevel;

} e_shell__command_context_t;

typedef struct _shell_command_context_list
{
    e_shell__command_context_t CommandList[CONFIG__E_SHELL_MAX_CMD]; /*!< The command table list */
    uint8_t numberOfCommandInList;                             /*!< The total command in list */
} e_shell__command_context_list_t;


typedef int32_t (*e_shell__read_char_t)(uint8_t *ch);
typedef int32_t (*e_shell__write_buf_t)(uint8_t *data_buf,uint32_t len);

typedef struct _shell_context_struct
{
    char *prompt;                 /*!< Prompt string */
    enum _fun_key_status stat;    /*!< Special key status */
    char *Description;            /*!< A textual description of the shell*/
    char line[CONFIG__E_SHELL_BUFFER_SIZE]; /*!< Consult buffer */
    uint32_t                    CurrentPrivilegeLevel;
    uint8_t cmd_num;              /*!< Number of user commands */
    uint8_t l_pos;                /*!< Total line position */
    uint8_t c_pos;                /*!< Current line position */
    uint8_t echo;                                 /*Determines if characters are echoed*/
    uint8_t QuietOnBadCommand;                                 /*Determines if characters are echoed*/
    
    e_shell__read_char_t	read_char;
    e_shell__write_buf_t	tx_buffer;

    uint16_t hist_current;                            /*!< Current history command in hist buff*/
    uint16_t hist_count;                              /*!< Total history command in hist buff*/
    char hist_buf[CONFIG__E_SHELL_HIST_MAX][CONFIG__E_SHELL_BUFFER_SIZE]; /*!< History buffer*/

    char  g_paramBuffer[CONFIG__E_SHELL_BUFFER_SIZE];

    e_shell__command_context_list_t        ShellCommands;

} e_shell__context_struct, *e_shell__context_t;


#if defined(__cplusplus)
extern "C" {
#endif /* _cplusplus */

int32_t e_shell__register_cmd(e_shell__context_t shell,
                              char *pcCommand, 
							  char *pcHelpString,
                              cmd_function_t  pFuncCallBack, 
                              uint32_t MinPrivilegeLevel        
                              );

int32_t e_shell__printf(const e_shell__context_struct * shell,const char *FormatString,...);

void e_shell__crunch(e_shell__context_t shell);

cmd_function_t shell__help_handler(e_shell__context_t shell, int32_t argc, char **argv);



#if defined(__cplusplus)
}
#endif

/*! @}*/

#endif /* _FSL_SHELL_H_ */
